"""Cython compilation of security modules.

Compiles ``security/hardware_lock.py``, ``security/integrity.py``,
and ``security/anti_tamper.py`` into native ``.so`` extensions via
Cython.  The original ``.py`` sources are removed after compilation
so the distributed bundle contains only opaque machine code.

Usage::

    cd ai-Puzzle-Solver-backend
    python build_scripts/compile_security.py

Prerequisites::

    pip install cython setuptools

This script is called by ``build_release.sh`` after fingerprint
injection and before PyInstaller packaging.
"""

from __future__ import annotations

import shutil
import sys
from pathlib import Path

_BACKEND_ROOT = Path(__file__).resolve().parent.parent

# Modules to compile (relative to backend root)
_SECURITY_MODULES = [
    "security/hardware_lock.py",
    "security/integrity.py",
    "security/anti_tamper.py",
]


def _create_setup_py(modules: list[str], build_dir: Path) -> Path:
    """Generate a temporary setup.py for Cython compilation.

    Parameters
    ----------
    modules : list[str]
        Relative paths to the .py files to compile.
    build_dir : Path
        Directory where setup.py will be written.

    Returns
    -------
    Path
        Path to the generated setup.py.
    """
    ext_lines = []
    for mod_path in modules:
        # Convert path to module name: security/hardware_lock.py → security.hardware_lock
        mod_name = mod_path.replace("/", ".").replace(".py", "")
        ext_lines.append(
            f'    Extension("{mod_name}", ["{mod_path}"]),'
        )

    setup_content = f'''\
"""Auto-generated setup.py for Cython compilation of security modules."""
from setuptools import setup
from Cython.Build import cythonize
from setuptools import Extension

extensions = [
{chr(10).join(ext_lines)}
]

setup(
    name="puzzlemind_security",
    ext_modules=cythonize(
        extensions,
        compiler_directives={{
            "language_level": "3",
            "boundscheck": False,
            "wraparound": False,
        }},
    ),
)
'''
    setup_path = build_dir / "setup.py"
    setup_path.write_text(setup_content, encoding="utf-8")
    return setup_path


def compile_security_modules() -> None:
    """Compile all security modules with Cython.

    1. Generate a temporary setup.py
    2. Run ``python setup.py build_ext --inplace``
    3. Move ``.so`` files to their original locations
    4. Remove ``.py`` sources and build artifacts
    """
    import subprocess

    print("=" * 55)
    print("PuzzleMind: Cython Security Compilation")
    print("=" * 55)
    print()

    # Verify all source files exist
    for mod_path in _SECURITY_MODULES:
        full_path = _BACKEND_ROOT / mod_path
        if not full_path.is_file():
            print(f"ERROR: Source not found: {full_path}")
            sys.exit(1)
        print(f"  Found: {mod_path}")

    # Generate setup.py in backend root
    setup_path = _create_setup_py(_SECURITY_MODULES, _BACKEND_ROOT)
    print(f"\nGenerated: {setup_path}")

    # Run Cython compilation
    print("\nCompiling with Cython...")
    result = subprocess.run(
        [sys.executable, "setup.py", "build_ext", "--inplace"],
        cwd=str(_BACKEND_ROOT),
        capture_output=True,
        text=True,
    )

    if result.returncode != 0:
        print(f"Cython compilation FAILED:\n{result.stderr}")
        sys.exit(1)

    print("Compilation successful.")

    # Verify .so files were created
    for mod_path in _SECURITY_MODULES:
        mod_name = Path(mod_path).stem
        mod_dir = _BACKEND_ROOT / Path(mod_path).parent
        # Look for .so or .pyd (Windows) files
        so_files = list(mod_dir.glob(f"{mod_name}*.so")) + \
                   list(mod_dir.glob(f"{mod_name}*.pyd"))
        if not so_files:
            print(f"ERROR: No compiled output for {mod_path}")
            sys.exit(1)
        for so in so_files:
            print(f"  Compiled: {so.name}")

    # Remove .py sources (keep .so only)
    print("\nRemoving Python sources...")
    for mod_path in _SECURITY_MODULES:
        py_path = _BACKEND_ROOT / mod_path
        if py_path.is_file():
            py_path.unlink()
            print(f"  Removed: {mod_path}")

    # Also remove .c files generated by Cython
    for mod_path in _SECURITY_MODULES:
        c_path = _BACKEND_ROOT / mod_path.replace(".py", ".c")
        if c_path.is_file():
            c_path.unlink()
            print(f"  Removed: {c_path.name}")

    # Clean up build artifacts
    setup_path.unlink(missing_ok=True)
    build_dir = _BACKEND_ROOT / "build"
    if build_dir.is_dir():
        shutil.rmtree(build_dir)
        print("  Removed: build/")

    print("\nCython compilation complete.")


if __name__ == "__main__":
    compile_security_modules()
